### ISSUE TITLE
[api feedback] BatcherExtensions should be on Renderer.

### ISSUE THREAD

**Issue by Thraka** [Jjagg/OpenWheels#3]
1. Should the extensions be on IRenderer instead?

   The methods in [OpenWheels.Rendering.ImageSharp/BatcherExtensions.cs](https://github.com/Jjagg/OpenWheels/blob/eb8186f77f53bc86dd27e82c0e5323d3b733c426/src/OpenWheels.Rendering.ImageSharp/BatcherExtensions.cs) don't seem to make sense to me. These methods use the renderer exclusively (or through the Batcher to the Renderer. 

1. I need something like the private `BatcherExtensions.RegisterImage` method.

   [BatcherExtensions.RegisterImage](https://github.com/Jjagg/OpenWheels/blob/eb8186f77f53bc86dd27e82c0e5323d3b733c426/src/OpenWheels.Rendering.ImageSharp/BatcherExtensions.cs#L138) is private but it's what I was trying to use. These extensions don't provide a `LoadTexture` overload that uses a file path, so I have to load it via `Image<Rgba32>` directly, which gives me an image object. I want to get that image object into the renderer as easily as possible.

**Comment by Jjagg** [comment]
Thanks for the feedback!

> These extensions don't provide a LoadTexture overload that uses a file path

What about [`LoadTexture`](https://github.com/Jjagg/OpenWheels/blob/eb8186f77f53bc86dd27e82c0e5323d3b733c426/src/OpenWheels.Rendering.ImageSharp/BatcherExtensions.cs#L30)? Is that not what you mean?

https://github.com/Jjagg/OpenWheels/blob/eb8186f77f53bc86dd27e82c0e5323d3b733c426/src/OpenWheels.Rendering.ImageSharp/BatcherExtensions.cs#L25-L30

> Should the extensions be on IRenderer instead?

The API is designed as is because I wanted to let `Batcher` be the class that's used for all `OpenWheels` rendering calls and have `IRenderer` just something users can instantiate and pass on creation, not having to touch it afterwards. However, I've been thinking about how responsibilities should be shared between `Batcher` and `IRenderer` lately and I would like to remove the dependency of `Batcher` on `IRenderer`. Instead, I'd like to open up the `Batcher` API. Right now it looks like Batcher does everything based on the API surface, but a clear separation between platform/resource-agnostic geometry batching (`Batcher`) and resource management + draw to target (`IRenderer`) would make a lot more sense.

One thing that I'm not entirely sure of how to handle with the new design is text. Right now the batcher only sends geometry + texture to the renderer. That's nice because it makes the rendering implementation simple, it does not have to be aware of fonts. But with the changed design, fonts being a resource, the batcher would not know how to render text. It would need to send a command to render font with a given id, size and text. I'm thinking about how to solve this so the renderer can stay simple while the API is consistent in what class manages resources.

A possible solution would be to split off texture management into an interface, `ITextureStorage`. Implementations can be used by the renderer and by a new platform-agnostic class responsible for rendering text, let's call it `TextRenderer`. `TextRenderer` serves specifically to translate a DrawText call to `Sprite =` and `FillRect` calls. This class could take on additional responsibility regarding font rendering, e.g. `Batcher.DrawText` could take a font size and `TextRenderer` could (based on some tolerance) either pick a pre-rendered font that's close enough in size and scale it or render the necessary chars at the given size and register it in `IResourceStorage` if no good enough size renders exist. Here's an image that explains the intention, A -> B mean A calls a method in B.

![openwheels](https://user-images.githubusercontent.com/14875382/50734403-e79f6a00-119e-11e9-9786-aacf472c9930.png)

This design simplifies the platform specific implementations and better splits up responsibilities. The resource storage implementation only needs to convert `Span<Color>` to a native texture, other loading mechanism (e.g. load from file) can be implemented with extension methods. The renderer implementation only needs to implement `BeginRender`, `DrawBatch` and `EndRender`. 

Like I said, the API is not stable yet, hope you don't mind...

Looking forward to your feedback :)

**Comment by Thraka** [comment]
Hi! OK I understand that Batcher-first paradigm. I think when playing around with this library and adapting some code, my original code was image first, so it loaded an image and stored it in a class that had a bunch of information used by my library. I then pass this object around to draw things. So my code method was to load the image first, then register it with the batcher.

So maybe I need to rework that.

I like your redesign suggestion. Can multiple renderers be used and point to the same texture storage? or is that stuff segmented out on the GPU and you can't cross reference? I need to explore your font system, that would give me a feature set I could use to match capabilities from [BearLibTerminal](http://foo.wyrd.name/en:bearlibterminal)

I totally don't mind having the unstable API, dont worry about that!

**Comment by Jjagg** [comment]
> Can multiple renderers be used and point to the same texture storage?

Yeah, sure. E.g. for Veldrid the texture storage will simply be a Map from texture id to a Veldrid Texture + source rectangle.
What do you want to achieve with multiple renderers? Have different implementations that draw things differently somehow?

> I need to explore your font system

I should probably add a DrawCharacter method, it makes sense to have and it'll make things easier for your application.

**Comment by Thraka** [comment]
> What do you want to achieve with multiple renderers? Have different implementations that draw things differently somehow?

Multiple windows 😄

**Comment by Jjagg** [comment]
I think that would work. It would be nice if you could use a single renderer for multiple windows, but there's 2 things I'm concerned about for that:
- I'm not sure you can share a Veldrid GraphicsDevice across multiple windows. OpenGL might ruin that. 
- The Veldrid IRenderer implementation currently does not support changing render target. That's a bit tricky currently because it caches the pipelines. I guess I could just cache pipelines per target, but not sure how to delete entries from the cache. Maybe give the user control over that?

**Comment by Thraka** [comment]
I'm not sure on the best way to do that anyhow. I'm just going of intuition. I figured I needed a diff graphics device for the other SDL window. Maybe not?

Anyhoo. When you say change render target do you mean you can't draw to texture either??

**Comment by Jjagg** [comment]
> Anyhoo. When you say change render target do you mean you can't draw to texture either??

Nope, not yet.

**Comment by Thraka** [comment]
Ack. that is the way my engine is built :) I'll have to work on that lol

**Comment by Jjagg** [comment]
If you only use 1 target, you can very easily work around it.

I'll implement it properly after the redesign.

**Comment by Jjagg** [comment]
> When you say change render target do you mean you can't draw to texture either

Should be fixed in 3c668d62f5131ca3b484ba240e1be49351e5b95d.
I also implemented the redesign, mostly like I said before. Only thing left is to implement the `ITextRenderer` so we can render text again.

**Comment by Thraka** [comment]
Oh sorry I misread. I thought you meant Veldrid only supported a single target. I see now you said Veldid IRenderer which is on your side. 👍

**Comment by mellinoe** [comment]
> I'm not sure you can share a Veldrid GraphicsDevice across multiple windows. OpenGL might ruin that.

For what it's worth, Veldrid does support this scenario through the Swapchain type: https://mellinoe.github.io/veldrid-docs/articles/swapchains.html. As you guessed, multiple Swapchains don't yet work with the OpenGL backend, but I have a branch with them partially implemented. That will make it's way back to master at some point; on other backends multiple Swapchains already work.

**Comment by Jjagg** [comment]
That is awesome :D I'm looking forward to GL support!
